export default [
  {
    "login": "gratuxri",
    "id": 1525579,
    "node_id": "MDQ6VXNlcjE1MjU1Nzk=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/1525579?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gratuxri",
    "html_url": "https://github.com/gratuxri",
    "followers_url": "https://api.github.com/users/gratuxri/followers",
    "following_url": "https://api.github.com/users/gratuxri/following{/other_user}",
    "gists_url": "https://api.github.com/users/gratuxri/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gratuxri/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gratuxri/subscriptions",
    "organizations_url": "https://api.github.com/users/gratuxri/orgs",
    "repos_url": "https://api.github.com/users/gratuxri/repos",
    "events_url": "https://api.github.com/users/gratuxri/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gratuxri/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ErwinZadeh",
    "id": 52617752,
    "node_id": "MDQ6VXNlcjUyNjE3NzUy",
    "avatar_url": "https://avatars1.githubusercontent.com/u/52617752?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ErwinZadeh",
    "html_url": "https://github.com/ErwinZadeh",
    "followers_url": "https://api.github.com/users/ErwinZadeh/followers",
    "following_url": "https://api.github.com/users/ErwinZadeh/following{/other_user}",
    "gists_url": "https://api.github.com/users/ErwinZadeh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ErwinZadeh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ErwinZadeh/subscriptions",
    "organizations_url": "https://api.github.com/users/ErwinZadeh/orgs",
    "repos_url": "https://api.github.com/users/ErwinZadeh/repos",
    "events_url": "https://api.github.com/users/ErwinZadeh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ErwinZadeh/received_events",
    "type": "User",
    "site_admin": false
  }
]
