export default {
    login:	"demkantor",
    id:	3387484,
    node_id:	"MDQ6VXNlcjMzODc0ODQ=",
    avatar_url:	"https://avatars2.githubusercontent.com/u/3387484?v=4",
    gravatar_id:	"",
    url:	"https://api.github.com/users/demkantor",
    html_url:	"https://github.com/demkantor",
    followers_url:	"https://api.github.com/users/demkantor/followers",
    following_url:	"https://api.github.com/users/demkantor/following{/other_user}",
    gists_url:	"https://api.github.com/users/demkantor/gists{/gist_id}",
    starred_url:	"https://api.github.com/users/demkantor/starred{/owner}{/repo}",
    subscriptions_url:	"https://api.github.com/users/demkantor/subscriptions",
    organizations_url:	"https://api.github.com/users/demkantor/orgs",
    repos_url:	"https://api.github.com/users/demkantor/repos",
    events_url:	"https://api.github.com/users/demkantor/events{/privacy}",
    received_events_url:	"https://api.github.com/users/demkantor/received_events",
    type:	"User",
    site_admin:	false,
    name:	"demkantor",
    company:	null,
    blog:	"https://www.demkantor.com/",
    location:	"minneapolis, mn",
    email:	null,
    hireable:	true,
    bio:	"Full stack software developer with a love for people and technology!",
    twitter_username:	null,
    public_repos:	81,
    public_gists:	6,
    followers:	2,
    following:	5,
    created_at:	"2013-01-26T03:33:53Z",
    updated_at:	"2020-07-29T19:31:18Z",
};
